'use strict';

const defaultClient = require('./client');

const METAFIELD_SET_MUTATION = `
  mutation metafieldsSet($metafields: [MetafieldsSetInput!]!) {
    metafieldsSet(metafields: $metafields) {
      metafields { id namespace key value }
      userErrors { field message code }
    }
  }
`;

const PRODUCT_METAFIELDS_QUERY = `
  query ProductMetafields($id: ID!) {
    product(id: $id) {
      metafields(first: 100, namespace: "custom") {
        nodes { namespace key type value }
      }
    }
  }
`;

const METAFIELD_DEFINITION_CREATE = `
  mutation CreateProductMetafieldDefinition($definition: MetafieldDefinitionInput!) {
    metafieldDefinitionCreate(definition: $definition) {
      createdDefinition { id namespace key }
      userErrors { field message code }
    }
  }
`;

const DEFINITIONS = [
  ['deal_enabled', 'Enable promo image', 'boolean', 'Generate a promotional social image for this product.'],
  ['deal_badge_text', 'Promo badge text', 'single_line_text_field', 'Optional badge text. Enter hide to remove the badge.'],
  ['deal_sale_price', 'Promo sale price', 'single_line_text_field', 'Optional displayed sale price. Enter hide to remove prices.'],
  ['deal_reg_price', 'Promo regular price', 'single_line_text_field', 'Optional displayed regular price.'],
  ['deal_title', 'Promo title', 'single_line_text_field', 'Optional promotional headline.'],
  ['og_image', 'Generated social image', 'single_line_text_field', 'Shopify CDN URL generated by the app.'],
  ['og_version', 'Generated image version', 'single_line_text_field', 'Internal image content version managed by the app.'],
  ['share_version', 'Social share version', 'single_line_text_field', 'Version used to create a fresh social sharing URL.'],
  ['og_image_input_hash', 'Image input version', 'single_line_text_field', 'Internal idempotency value managed by the app.'],
];

const OVERRIDE_KEYS = ['deal_enabled', 'deal_badge_text', 'deal_sale_price', 'deal_reg_price', 'deal_title'];
const APP_MANAGED_KEYS = new Set(['og_image', 'og_version', 'share_version', 'og_image_input_hash']);

function graphData(response, operation) {
  if (response.data?.errors?.length) {
    throw new Error(`${operation} GraphQL error: ${response.data.errors.map(error => error.message).join(', ')}`);
  }
  return response.data?.data;
}

async function ensureProductMetafieldDefinitions(client = defaultClient) {
  const results = [];
  for (const [key, name, type, description] of DEFINITIONS) {
    const response = await client.post('/graphql.json', {
      query: METAFIELD_DEFINITION_CREATE,
      variables: {
        definition: {
          namespace: 'custom',
          key,
          name,
          description,
          type,
          ownerType: 'PRODUCT',
          access: { storefront: 'PUBLIC_READ' },
        },
      },
    });
    const payload = graphData(response, 'metafieldDefinitionCreate')?.metafieldDefinitionCreate;
    const blockingErrors = (payload?.userErrors || []).filter(error =>
      error.code !== 'TAKEN' && !/already exists|in use/i.test(error.message)
    );
    if (blockingErrors.length) {
      throw new Error(`Definition ${key}: ${blockingErrors.map(error => error.message).join(', ')}`);
    }
    results.push({ key, created: Boolean(payload?.createdDefinition) });
  }
  return results;
}

async function setMetafields(metafields, client = defaultClient) {
  const response = await client.post('/graphql.json', {
    query: METAFIELD_SET_MUTATION,
    variables: { metafields },
  });
  const payload = graphData(response, 'metafieldsSet')?.metafieldsSet;
  if (payload?.userErrors?.length) {
    throw new Error(`metafieldsSet error: ${payload.userErrors.map(error => error.message).join(', ')}`);
  }
  return payload?.metafields || [];
}

async function updateProductMetafields(productId, imageUrl, ogVersion, shareVersion, inputHash, client = defaultClient) {
  const ownerId = `gid://shopify/Product/${productId}`;
  return setMetafields([
    { ownerId, namespace: 'custom', key: 'og_version', value: ogVersion, type: 'single_line_text_field' },
    { ownerId, namespace: 'custom', key: 'og_image', value: imageUrl, type: 'single_line_text_field' },
    { ownerId, namespace: 'custom', key: 'share_version', value: shareVersion, type: 'single_line_text_field' },
    { ownerId, namespace: 'custom', key: 'og_image_input_hash', value: inputHash, type: 'single_line_text_field' },
  ], client);
}

async function updateProductShareVersion(productId, shareVersion, client = defaultClient) {
  return setMetafields([{
    ownerId: `gid://shopify/Product/${productId}`,
    namespace: 'custom',
    key: 'share_version',
    value: shareVersion,
    type: 'single_line_text_field',
  }], client);
}

function parseBoolean(value) {
  if (value === true || value === 'true') return true;
  if (value === false || value === 'false') return false;
  return null;
}

async function fetchProductOverrides(productId, client = defaultClient) {
  try {
    const response = await client.post('/graphql.json', {
      query: PRODUCT_METAFIELDS_QUERY,
      variables: { id: `gid://shopify/Product/${productId}` },
    });
    const product = graphData(response, 'ProductMetafields')?.product;
    if (!product) return { _notFound: true };
    const metafields = product.metafields?.nodes || [];
    const result = {};
    for (const key of OVERRIDE_KEYS) {
      const metafield = metafields.find(item => item.key === key);
      result[key] = key === 'deal_enabled'
        ? parseBoolean(metafield?.value)
        : metafield?.value?.trim() || null;
    }
    result._storedHash = metafields.find(item => item.key === 'og_image_input_hash')?.value ?? null;
    result._storedOgVersion = metafields.find(item => item.key === 'og_version')?.value ?? null;
    result._storedShareVersion = metafields.find(item => item.key === 'share_version')?.value ?? null;
    result._shareMetafields = metafields
      .filter(item => !APP_MANAGED_KEYS.has(item.key))
      .map(item => ({ namespace: item.namespace, key: item.key, type: item.type, value: item.value }))
      .sort((left, right) => `${left.namespace}.${left.key}`.localeCompare(`${right.namespace}.${right.key}`));
    return result;
  } catch (err) {
    if (err.response?.status === 404) return { _notFound: true };
    console.warn('[metafields] fetchProductOverrides failed (non-fatal):', err.message);
    return {};
  }
}

module.exports = {
  DEFINITIONS,
  ensureProductMetafieldDefinitions,
  fetchProductOverrides,
  updateProductMetafields,
  updateProductShareVersion,
};
