# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b4a22689fe1a3b175c2775f2850b2b0"
name = "Simplex Deals Social Image"
application_url = "https://simplex-deals-social-image.vercel.app"
embedded = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update"]
uri = "/webhooks/shopify/products"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/shopify/app-uninstalled"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/webhooks/shopify/customers-data-request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/webhooks/shopify/customers-redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/webhooks/shopify/shop-redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_files,write_files,read_publications,write_publications"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://simplex-deals-social-image.vercel.app/auth/callback"]
